export const melodies = [
  {
    tempos: [{ qpm: 120 }],
    notes: [
      { pitch: 45, quantizedStartStep: '0', quantizedEndStep: '4' },
      { pitch: 50, quantizedStartStep: '4', quantizedEndStep: '6' },
      { pitch: 52, quantizedStartStep: '6', quantizedEndStep: '8' },
      { pitch: 53, quantizedStartStep: '8', quantizedEndStep: '10' },
      { pitch: 52, quantizedStartStep: '10', quantizedEndStep: '12' },
      { pitch: 50, quantizedStartStep: '12', quantizedEndStep: '16' },
      { pitch: 48, quantizedStartStep: '16', quantizedEndStep: '20' },
      { pitch: 50, quantizedStartStep: '20', quantizedEndStep: '26' },
      { pitch: 45, quantizedStartStep: '26', quantizedEndStep: '28' },
      { pitch: 45, quantizedStartStep: '28', quantizedEndStep: '32' },
    ],
    quantizationInfo: { stepsPerQuarter: 4 },
    totalQuantizedSteps: '256',
  },
  {
    tempos: [{ qpm: 120 }],
    notes: [
      { pitch: 50, quantizedStartStep: '0', quantizedEndStep: '2' },
      { pitch: 52, quantizedStartStep: '2', quantizedEndStep: '4' },
      { pitch: 52, quantizedStartStep: '4', quantizedEndStep: '5' },
      { pitch: 52, quantizedStartStep: '5', quantizedEndStep: '6' },
      { pitch: 50, quantizedStartStep: '6', quantizedEndStep: '7' },
      { pitch: 52, quantizedStartStep: '7', quantizedEndStep: '8' },
      { pitch: 50, quantizedStartStep: '8', quantizedEndStep: '9' },
      { pitch: 52, quantizedStartStep: '9', quantizedEndStep: '10' },
      { pitch: 50, quantizedStartStep: '10', quantizedEndStep: '12' },
      { pitch: 52, quantizedStartStep: '12', quantizedEndStep: '14' },
      { pitch: 57, quantizedStartStep: '14', quantizedEndStep: '16' },
      { pitch: 48, quantizedStartStep: '16', quantizedEndStep: '18' },
      { pitch: 48, quantizedStartStep: '18', quantizedEndStep: '20' },
      { pitch: 48, quantizedStartStep: '20', quantizedEndStep: '24' },
      { pitch: 48, quantizedStartStep: '24', quantizedEndStep: '26' },
      { pitch: 48, quantizedStartStep: '26', quantizedEndStep: '28' },
      { pitch: 36, quantizedStartStep: '28', quantizedEndStep: '32' },
    ],
    quantizationInfo: { stepsPerQuarter: 4 },
    totalQuantizedSteps: '256',
  },
  {
    tempos: [{ qpm: 120 }],
    notes: [
      { pitch: 50, quantizedStartStep: '0', quantizedEndStep: '1' },
      { pitch: 53, quantizedStartStep: '1', quantizedEndStep: '2' },
      { pitch: 58, quantizedStartStep: '2', quantizedEndStep: '3' },
      { pitch: 58, quantizedStartStep: '3', quantizedEndStep: '4' },
      { pitch: 58, quantizedStartStep: '4', quantizedEndStep: '5' },
      { pitch: 58, quantizedStartStep: '5', quantizedEndStep: '6' },
      { pitch: 53, quantizedStartStep: '6', quantizedEndStep: '7' },
      { pitch: 53, quantizedStartStep: '7', quantizedEndStep: '8' },
      { pitch: 53, quantizedStartStep: '8', quantizedEndStep: '9' },
      { pitch: 53, quantizedStartStep: '9', quantizedEndStep: '10' },
      { pitch: 65, quantizedStartStep: '10', quantizedEndStep: '11' },
      { pitch: 65, quantizedStartStep: '11', quantizedEndStep: '12' },
      { pitch: 65, quantizedStartStep: '12', quantizedEndStep: '13' },
      { pitch: 65, quantizedStartStep: '13', quantizedEndStep: '14' },
      { pitch: 65, quantizedStartStep: '14', quantizedEndStep: '15' },
      { pitch: 53, quantizedStartStep: '15', quantizedEndStep: '16' },
      { pitch: 57, quantizedStartStep: '16', quantizedEndStep: '17' },
      { pitch: 57, quantizedStartStep: '17', quantizedEndStep: '18' },
      { pitch: 57, quantizedStartStep: '18', quantizedEndStep: '19' },
      { pitch: 57, quantizedStartStep: '19', quantizedEndStep: '20' },
      { pitch: 57, quantizedStartStep: '20', quantizedEndStep: '21' },
      { pitch: 57, quantizedStartStep: '21', quantizedEndStep: '22' },
      { pitch: 57, quantizedStartStep: '22', quantizedEndStep: '23' },
      { pitch: 57, quantizedStartStep: '23', quantizedEndStep: '24' },
      { pitch: 57, quantizedStartStep: '24', quantizedEndStep: '25' },
      { pitch: 57, quantizedStartStep: '25', quantizedEndStep: '26' },
      { pitch: 57, quantizedStartStep: '26', quantizedEndStep: '27' },
      { pitch: 57, quantizedStartStep: '27', quantizedEndStep: '28' },
      { pitch: 64, quantizedStartStep: '28', quantizedEndStep: '29' },
      { pitch: 64, quantizedStartStep: '29', quantizedEndStep: '30' },
      { pitch: 64, quantizedStartStep: '30', quantizedEndStep: '31' },
      { pitch: 60, quantizedStartStep: '31', quantizedEndStep: '32' },
    ],
    quantizationInfo: { stepsPerQuarter: 4 },
    totalQuantizedSteps: '256',
  },
];
