export const melodies = [
  {
    tempos: [{ qpm: 120 }],
    notes: [
      { pitch: 57, quantizedStartStep: '0', quantizedEndStep: '2' },
      { pitch: 57, quantizedStartStep: '2', quantizedEndStep: '3' },
      { pitch: 59, quantizedStartStep: '3', quantizedEndStep: '4' },
      { pitch: 57, quantizedStartStep: '4', quantizedEndStep: '16' },
      { pitch: 59, quantizedStartStep: '16', quantizedEndStep: '19' },
      { pitch: 60, quantizedStartStep: '19', quantizedEndStep: '20' },
      { pitch: 59, quantizedStartStep: '20', quantizedEndStep: '32' },
      { pitch: 64, quantizedStartStep: '32', quantizedEndStep: '35' },
      { pitch: 65, quantizedStartStep: '35', quantizedEndStep: '36' },
      { pitch: 64, quantizedStartStep: '36', quantizedEndStep: '48' },
      { pitch: 71, quantizedStartStep: '48', quantizedEndStep: '51' },
      { pitch: 72, quantizedStartStep: '51', quantizedEndStep: '52' },
      { pitch: 71, quantizedStartStep: '52', quantizedEndStep: '58' },
      { pitch: 69, quantizedStartStep: '58', quantizedEndStep: '60' },
      { pitch: 67, quantizedStartStep: '60', quantizedEndStep: '68' },
    ],
    quantizationInfo: { stepsPerQuarter: 4 },
    totalQuantizedSteps: '256',
  },
  {
    tempos: [{ qpm: 120 }],
    notes: [
      { pitch: 69, quantizedStartStep: '0', quantizedEndStep: '2' },
      { pitch: 65, quantizedStartStep: '2', quantizedEndStep: '3' },
      { pitch: 64, quantizedStartStep: '3', quantizedEndStep: '4' },
      { pitch: 69, quantizedStartStep: '4', quantizedEndStep: '10' },
      { pitch: 57, quantizedStartStep: '12', quantizedEndStep: '16' },
      { pitch: 59, quantizedStartStep: '16', quantizedEndStep: '19' },
      { pitch: 60, quantizedStartStep: '19', quantizedEndStep: '20' },
      { pitch: 60, quantizedStartStep: '20', quantizedEndStep: '23' },
      { pitch: 64, quantizedStartStep: '23', quantizedEndStep: '24' },
      { pitch: 64, quantizedStartStep: '24', quantizedEndStep: '31' },
      { pitch: 60, quantizedStartStep: '31', quantizedEndStep: '32' },
      { pitch: 59, quantizedStartStep: '32', quantizedEndStep: '34' },
      { pitch: 60, quantizedStartStep: '35', quantizedEndStep: '36' },
      { pitch: 64, quantizedStartStep: '36', quantizedEndStep: '39' },
      { pitch: 62, quantizedStartStep: '39', quantizedEndStep: '40' },
      { pitch: 64, quantizedStartStep: '40', quantizedEndStep: '44' },
      { pitch: 64, quantizedStartStep: '44', quantizedEndStep: '52' },
      { pitch: 57, quantizedStartStep: '52', quantizedEndStep: '55' },
      { pitch: 60, quantizedStartStep: '55', quantizedEndStep: '56' },
      { pitch: 59, quantizedStartStep: '56', quantizedEndStep: '59' },
      { pitch: 56, quantizedStartStep: '59', quantizedEndStep: '60' },
      { pitch: 57, quantizedStartStep: '60', quantizedEndStep: '64' },
      { pitch: 67, quantizedStartStep: '64', quantizedEndStep: '67' },
      { pitch: 69, quantizedStartStep: '67', quantizedEndStep: '68' },
      { pitch: 66, quantizedStartStep: '68', quantizedEndStep: '72' },
      { pitch: 64, quantizedStartStep: '72', quantizedEndStep: '256' },
    ],
    quantizationInfo: { stepsPerQuarter: 4 },
    totalQuantizedSteps: '256',
  },
  {
    tempos: [{ qpm: 120 }],
    notes: [
      { pitch: 57, quantizedStartStep: '1', quantizedEndStep: '2' },
      { pitch: 60, quantizedStartStep: '3', quantizedEndStep: '4' },
      { pitch: 64, quantizedStartStep: '4', quantizedEndStep: '10' },
      { pitch: 57, quantizedStartStep: '11', quantizedEndStep: '12' },
      { pitch: 60, quantizedStartStep: '12', quantizedEndStep: '13' },
      { pitch: 65, quantizedStartStep: '13', quantizedEndStep: '14' },
      { pitch: 64, quantizedStartStep: '15', quantizedEndStep: '16' },
      { pitch: 65, quantizedStartStep: '16', quantizedEndStep: '17' },
      { pitch: 64, quantizedStartStep: '17', quantizedEndStep: '19' },
      { pitch: 62, quantizedStartStep: '19', quantizedEndStep: '20' },
      { pitch: 60, quantizedStartStep: '20', quantizedEndStep: '21' },
      { pitch: 53, quantizedStartStep: '21', quantizedEndStep: '22' },
      { pitch: 52, quantizedStartStep: '23', quantizedEndStep: '24' },
      { pitch: 57, quantizedStartStep: '24', quantizedEndStep: '25' },
      { pitch: 62, quantizedStartStep: '25', quantizedEndStep: '32' },
      { pitch: 62, quantizedStartStep: '32', quantizedEndStep: '33' },
      { pitch: 59, quantizedStartStep: '33', quantizedEndStep: '34' },
      { pitch: 57, quantizedStartStep: '35', quantizedEndStep: '36' },
      { pitch: 52, quantizedStartStep: '37', quantizedEndStep: '38' },
      { pitch: 55, quantizedStartStep: '39', quantizedEndStep: '40' },
      { pitch: 60, quantizedStartStep: '41', quantizedEndStep: '43' },
      { pitch: 64, quantizedStartStep: '43', quantizedEndStep: '44' },
      { pitch: 67, quantizedStartStep: '45', quantizedEndStep: '47' },
      { pitch: 64, quantizedStartStep: '47', quantizedEndStep: '53' },
      { pitch: 57, quantizedStartStep: '53', quantizedEndStep: '54' },
      { pitch: 57, quantizedStartStep: '55', quantizedEndStep: '56' },
      { pitch: 60, quantizedStartStep: '56', quantizedEndStep: '57' },
      { pitch: 65, quantizedStartStep: '57', quantizedEndStep: '58' },
      { pitch: 64, quantizedStartStep: '59', quantizedEndStep: '60' },
      { pitch: 65, quantizedStartStep: '60', quantizedEndStep: '61' },
      { pitch: 69, quantizedStartStep: '61', quantizedEndStep: '64' },
      { pitch: 62, quantizedStartStep: '64', quantizedEndStep: '65' },
      { pitch: 57, quantizedStartStep: '65', quantizedEndStep: '66' },
      { pitch: 59, quantizedStartStep: '67', quantizedEndStep: '68' },
      { pitch: 60, quantizedStartStep: '68', quantizedEndStep: '69' },
    ],
    quantizationInfo: { stepsPerQuarter: 4 },
    totalQuantizedSteps: '256',
  },
];
